apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-app
  namespace: echo
spec:
  project: echo
  source:
    repoURL: https://github.com/marcel-dempers/docker-development-youtube-series.git
    targetRevision: HEAD
    path: argo/example-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: echo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true