FROM amitkshirsagar13/devops-jenkins-agent-generic:latest

USER root

ENV TERRAFORM_VERSION=1.1.0

RUN apk --no-cache update && \
  curl -sL https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -o /tmp/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
  unzip /tmp/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/bin && \
  rm -rf /var/tmp/ && \
  rm -rf /tmp/* && \
  rm -rf /var/cache/apk/*

USER jenkins