# ---
# apiVersion: v1
# kind: namespace
# metadata:
#   name: kube-monitor
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kube-monitor
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kube-monitor
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:6.5.0
        resources:
          limits:
            cpu: 1000m
            memory: 600Mi
          requests:
            cpu: 100m
            memory: 400Mi
        env:
          - name: ELASTICSEARCH_URL
            value: http://es.default.svc.cluster.local:9200
          # - name: SERVER_BASEPATH 
          #   value: /kibana
        ports:
        - containerPort: 5601
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: kube-monitor
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  # http://kibana.k8cluster.local/
  - host: kibana.k8cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kibana
            port:
              number: 5601