pipeline {
  agent { label 'terraform-kubernetes-slave' }

  parameters {
    choice(name: 'EnvName', choices: ['local','int','stg','e2e','live'], description: 'Cluster EnvName')
    choice(name: 'Region', choices: ['us-east-1','us-east-2','global'], description: 'Cluster Region')
    choice(name: 'Module', choices: ['security','compute','infra','s3','all'], description: 'Modules to execute')
    choice(name: 'SubModule', choices: ['charts','eks','all'], description: 'Folders to execute')
    choice(name: 'Action', choices: ['plan','apply','destroy'], description: 'Terraform Action')
    choice(name: 'Approve', choices: ['no','yes'], description: 'Terraform Action')
    choice(name: 'Debug', choices: ['no','yes'], description: 'Terraform Debug')
    checkboxParameter(name: 'ItemList', format: 'JSON',
                pipelineSubmitContent: 
                '{"CheckboxParameter": [{"key": "charts","value": "charts"},{"key": "security","value": "security"},{"key": "s3","value": "s3"}]}', 
                description: '')
  }

  options {
    ansiColor('xterm')
  }

  environment {
    AWS_DEFAULT_REGION = "us-east-1"
    ENVKEY = "${EnvName.toUpperCase()}"
    KUBEHOST = "${ENVKEY}_KUBE_HOST"
    KUBETOKEN = "${ENVKEY}_JENKINS_KUBE_TOKEN"
    KEY = "${ENVKEY}_AWS_ACCESS_KEY_ID"
    SECRET = "${ENVKEY}_AWS_SECRET_ACCESS_KEY"
  }

  stages {
    stage("Prepare") {
      steps {
        script {
          userInfo_Id = userInfo('USERID')
          userInfo_Name = userInfo('USER')
          userInfo_Email = userInfo('EMAIL')

          sh """
            echo ID: $userInfo_Id Name: $userInfo_Name Email: $userInfo_Email
          """
          itemList = env.ItemList
          sh """
            echo itemList: $itemList
          """

          clone("https://github.com/amitkshirsagar13/devops.git")
        }
      }
    }
    
    stage("Terraform Request") {
      steps {
        script {
          terraformEnv = env.EnvName
          terraformRegion = env.Region
          terraformModule = env.Module
          terraformSubModule = ''
          terraformAction = env.Action
          sh """
            echo Terraform $terraformEnv Module $terraformModule with $terraformAction
          """
          terraformPath = "terragrunt/aws/" + terraformEnv + "/" + terraformRegion
          if ( terraformModule == 'compute') {
            if (env.SubModule != 'all') {
              terraformSubModule = "/" + env.SubModule
            }
          }
          if ( terraformModule != 'all') {
            terraformPath = terraformPath + "/" + terraformModule + terraformSubModule
          }
        }
      }
    }
    
    stage("Terraform Init") {
      steps {
        script {
          debug = env.Debug
          sh "echo Debug: $debug"
          if(debug == 'yes') {
            environment {
              TF_LOG = "TRACE"
            }
          }
          terraformInit(terraformAction, terraformPath)
        }
      }
    }
    
    stage("Terraform Plan") {
      when {
        expression { action == 'plan' || action == 'apply'  || action == 'destroy' }
      }
      steps {
        script {
          terraformPlan(terraformModule, terraformAction, terraformPath)
        }
      }
    }
    
    stage('Approval') {
      when {
        expression { action == 'apply' || action == 'destroy' }
      }
      steps {
        script {
          approval = env.Approve
          sh "echo Auto Approval: $approval"
          if(approval == 'no') {
            sh """echo Auto Approval Disabled, hence waiting"""
            timeout(time:5, unit:'MINUTES') {
              def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
            }
          } else {
            sh "echo Auto Approval Enabled, hence proceeding"
          }
        }
      }
    }
    
    stage("Terraform Apply") {
      when {
        expression { action == 'apply' }
      }
      steps {
        script {
          terraformApply(terraformModule, terraformAction, terraformPath)
        }
      }
    }

    stage("Terraform Destroy") {
      when {
        expression { action == 'destroy' }
      }
      steps {
        script {
          terraformDestroy(terraformModule, terraformAction, terraformPath)
        }
      }
    }
  }
}