pipeline {
  agent { label 'terraform-docker-slave' }

  parameters {
    choice(name: 'Level', choices: ['local','int','stg','e2e','live'], description: 'Cluster level')
    choice(name: 'Region', choices: ['us-east-1','us-east-2','global'], description: 'Cluster Region')
    choice(name: 'Module', choices: ['security','infra','eks','s3','all'], description: 'Modules to execute')
    choice(name: 'Action', choices: ['plan','apply','destroy'], description: 'Terraform Action')
    choice(name: 'Approve', choices: ['yes','no'], description: 'Terraform Action')
  }

  options {
    ansiColor('xterm')
  }

  environment {
    AWS_DEFAULT_REGION = "us-east-1"
    ENVKEY = "${Level.toUpperCase()}"
    KEY = "${ENVKEY}_AWS_ACCESS_KEY_ID"
    SECRET = "${ENVKEY}_AWS_SECRET_ACCESS_KEY"
    AWS_ACCESS_KEY_ID     = credentials("${KEY}")
    AWS_SECRET_ACCESS_KEY = credentials("${SECRET}")
  }

  stages {
    stage("Terraform Request") {
      steps {
        script {
          sh """
            echo ENVKEY $ENVKEY KEY $KEY SECRET $SECRET
          """
          sh """
            echo AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
          """
        }
      }
    }
  }

}