version: "3.6"

services:
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json

  jenkins:
    environment:
      CASC_VAULT_FILE: /run/secrets/jcasc_vault
    restart: always
    container_name: jenkins
    image: amitkshirsagar13/devops/jenkins:latest
    ports:
      - 3000:8080
      - 50000:50000
    secrets:
      - jcasc_vault
    links:
      - "vault:vault"
    depends_on:
      - "vault"


secrets:
  jcasc_vault:
    file: ./secrets/jcasc_vault