version: "3.6"

services:
  jenkins:
    environment:
      CASC_VAULT_FILE: /run/secrets/jcasc_vault
    restart: always
    container_name: jenkins-master
    image: amitkshirsagar13/devops-jenkin:production
    hostname: jenkins-master
    user: root
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/jenkins:/var/jenkins_home"
    # group_add:
    #   - 994 #docker group id
    ports:
      - 3000:8080
      - 50000:50000
    secrets:
      - jcasc_vault
    extra_hosts:
        - "vault:192.168.1.131" #host and ip

    



secrets:
  jcasc_vault:
    file: ./secrets/jcasc_vault