jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  clouds:
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"
        templates:
          - labelString: "generic-docker-slave"
            dockerTemplateBase:
              image: "amitkshirsagar13/devops-jenkins-agent-docker:latest"
              mounts:
                - "type=bind,source=/var/jenkins/.m2,destination=/home/jenkins/.m2"
                - "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock"
            remoteFs: "/home/jenkins"
            connector:
              attach:
                user: "root"
            instanceCapStr: "5"
            retentionStrategy:
              idleMinutes: 1
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
        - id: "dev"
          password: "dev"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Job/Build:dev"
        - "Job/Cancel:dev"
        - "Job/Read:dev"
        - "Job/Workspace:dev"
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
        - "Run/Replay:dev"
        - "Run/Update:dev"
  # globalNodeProperties:
  # - envVars:
  #     env:
  #     - key: VARIABLE1
  #       value: foo
  #     - key: VARIABLE2
  #       value: bar
  # nodes:
  #   - permanent:
  #       name: "static-agent"
  #       remoteFS: "/home/jenkins"
  #       launcher:
  #         jnlp:
  #           workDirSettings:
  #             disabled: true
  #             failIfWorkDirIsMissing: false
  #             internalDir: "remoting"
  #             workDirPath: "/tmp"
  # slaveAgentPort: 50000
  # agentProtocols:
  #   - "jnlp2"

jobs:
  - script: |
      multibranchPipelineJob('sample-service') {
        branchSources {
          git {
            id = 'sample-service'
            remoteName = 'origin'
            remote('https://github.com/amitkshirsagar13/sample-service.git')
            includes('feature*')
            excludes('')
          }
        }
      }

      pipelineJob('generic-docker-slave-test') {
        description("Need to have defined docker cloud plugin with label generic-docker-slave agent")
        definition {
          cps {
            script('''
              agentName = "generic-docker-slave"
              agentLabel = "${println 'Right Now the Agent Name is ' + agentName; return agentName}"

              pipeline {
                agent { label 'generic-docker-slave' }
                stages {
                  stage('Location') {
                    steps {
                      script {
                        agentName = "generic-docker-slave"
                      }
                      sh "pwd"
                      sh "ls -ltraR /home/jenkins"
                    }
                  }
                  stage('Checking') {
                    steps {
                      script {
                        println agentLabel
                        println agentName
                      }
                    }
                  }
                  stage('Run Tests') {
                    parallel ({
                      stage('Test On Windows') {
                        agent {
                          label agentName
                        }
                        steps {
                          sh "sleep 2m"
                        }
                      }
                      stage('Test On Linux') {
                        agent {
                          label agentName
                        }
                        steps {
                          sh "sleep 1m"
                        }
                      }
                      stage('Test On Mac') {
                        agent {
                          label agentName
                        }
                        steps {
                          sh "sleep 90"
                          sh "docker ps"
                          error 'Error in group2 processing'
                        }
                      }
                    }, failFast: true)
                  }
                  stage('Final') {
                    agent { label agentLabel }

                    steps {
                      script {
                        println agentLabel
                        println agentName
                      }
                    }
                  }
                }
              }
            '''.stripIndent())
            sandbox()     
          }
        }
      }

      pipelineJob('jte-demo-scripted') {
        def repo = 'https://github.com/amitkshirsagar13/sample-service.git'
        description("Pipeline for jte-scripted")
        displayName("Sample-Service-jte-scripted")
        definition {
          cpsScm {
            scm {
              git {
                remote { 
                  url(repo) 
                  credentials('github-ci-user')
                }
                branches('master', '**/feature*')
                scriptPath('Jenkinsfile.jte-scripted')
                extensions { }  // required as otherwise it may try to tag the repo, which you may not want
              }
            }
          }
        }
      }

      pipelineJob('jte-demo-declarative') {
        def repo = 'https://github.com/amitkshirsagar13/sample-service.git'
        description("Pipeline for jte-declarative")
        displayName("Sample-Service-jte-declarative")
        definition {
          cpsScm {
            scm {
              git {
                remote { 
                  url(repo) 
                  credentials('github-ci-user')
                }
                branches('master', '**/feature*')
                scriptPath('Jenkinsfile.jte-declarative')
                extensions { }  // required as otherwise it may try to tag the repo, which you may not want
              }
            }
          }
        }
      }

credentials:
  system:
    domainCredentials:
      - credentials:
          #######
          # User Auth
          #######
          - usernamePassword:
              scope: "GLOBAL"
              id: "github-ci-user"
              description: "Github CI ${github-ci-user} Credentials from Vault"
              username: "${github-ci-user}"
              password: "${github-ci-password}"
          ########
          # Tokens
          ########
          - string:
              scope: "GLOBAL"
              id: "github-ci-token"
              description: "Github CI Global Token ${jenkins-tokens/github-ci-token} from File"
              secret: "${jenkins-tokens/github-ci-token}"
          ########
          # SSH Keys
          ########
          # - basicSSHUserPrivateKey:
          #     scope: "GLOBAL"
          #     id: "deploy-key-shared-library"
          #     username: "root"
          #     passphrase: ""
          #     description: "Deploy key for global shared library"
          #     privateKeySource:
          #       directEntry:
          #         privateKey: "${jenkins-ssh-keys/deploy-key-shared-library}"
          # - basicSSHUserPrivateKey:
          #     scope: "GLOBAL"
          #     id: "ssh-agent-access-key"
          #     username: "ubuntu"
          #     passphrase: ""
          #     description: "SSH key to access agents"
          #     privateKeySource:
          #       directEntry:
          #         privateKey: "${jenkins-ssh-keys/ssh-agent-access-key}"

tool:
  jdk:
    installations:
      # - name: "open-jdk8"
      #   properties:
      #     - installSource:
      #         installers:
      #           - adoptOpenJdkInstaller:
      #               id: "jdk8u232-b09"
      - name: "jdk8"
        properties:
          - installSource:
              installers:
                - jdkInstaller:
                    acceptLicense: true
                    id: "jdk-8u221-oth-JPR"
  maven: # (1)
    installations:
    - name: "maven"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.8.2"
  dockerTool:
    installations:
    - name: "docker"
      properties:
      - installSource:
          installers:
          - fromDocker:
              version: "latest"
  git:
    installations:
    - home: "git"
      name: "Default"
unclassified:
  globalLibraries:
    libraries:
      - name: "devops-ci-lib"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "git@github.com:amitkshirsagar13/base-pipeline.git"
                credentialsId: "github-ci-user"
  templateGlobalConfig:
    tier:
      configurationProvider: "null"
      librarySources:
      - libraryProvider:
          scm:
            baseDir: "libraries"
            scm:
              git:
                branches:
                - name: "*/main"
                buildChooser: "default"
                userRemoteConfigs:
                - credentialsId: "github-ci-user"
                  url: "https://github.com/amitkshirsagar13/devops.git"