---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-configuration
  namespace: monitoring
  labels:
    app: jaeger
    jaeger-infra: configuration
data:
  span-storage-type: kafka
  span-storage-type-persist: elasticsearch
  query: |
    es:
      server-urls: http://es.monitoring:9200
      index-prefix: jaeger-es
  collector: |
    kafka:
      brokers: kafka-service.infra:9092 # kafka.local
      producer:
        brokers: kafka-service.infra:9092
        topic: jaeger-spans
    es:
      server-urls: http://es.monitoring:9200
      index-prefix: jaeger-es
      num-replicas: 0
      num-shards: 1
    collector:
      zipkin:
        http-port: 9411
  ingester: |
    kafka:
      brokers: kafka-service.infra:9092
      consumer:
        brokers: kafka-service.infra:9092
        topic: jaeger-spans
        group-id: jaeger-ingester
    es:
      server-urls: http://es.monitoring:9200
      index-prefix: jaeger-es
      num-replicas: 0
      num-shards: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector
  namespace: monitoring
  labels:
    app: jaeger
    jaeger-infra: collector-deployment
spec:
  selector:
    matchLabels:
      app: jaeger-collector
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jaeger-collector
        jaeger-infra: collector-pod
    spec:
      containers:
        - image: jaegertracing/jaeger-collector:1.21 # 1.28 # 1.6.0
          name: jaeger-collector
          args: ["--config-file=/conf/collector.yaml"]
          ports:
            - containerPort: 14250
              protocol: TCP
            - containerPort: 14267
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
            - containerPort: 14269
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
          volumeMounts:
            - name: jaeger-configuration-volume
              mountPath: /conf
          env:
            - name: SPAN_STORAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: jaeger-configuration
                  key: span-storage-type
          resources:
            requests:
              memory: 300M
              cpu: 250m
            limits:
              memory: 300M
              cpu: 250m
      hostAliases:
      - ip: "192.168.65.2"
        hostnames:
        - "kafka.local"
      volumes:
        - configMap:
            name: jaeger-configuration
            items:
              - key: collector
                path: collector.yaml
          name: jaeger-configuration-volume
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: monitoring
  labels:
    app: jaeger
    jaeger-infra: collector-service
spec:
  ports:
    - name: jaeger-collector-grpc
      port: 14250
      protocol: TCP
      targetPort: 14250
  selector:
    jaeger-infra: collector-pod
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query
  namespace: monitoring
  labels:
    app: jaeger
    jaeger-infra: query-deployment
spec:
  selector:
    matchLabels:
      app: jaeger-query
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jaeger-query
        jaeger-infra: query-pod
    spec:
      containers:
        - image: jaegertracing/jaeger-query:1.28 # 1.6.0
          name: jaeger-query
          args: ["--config-file=/conf/query.yaml"]
          ports:
            - containerPort: 16686
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/"
              port: 16687
          volumeMounts:
            - name: jaeger-configuration-volume
              mountPath: /conf
          env:
            - name: SPAN_STORAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: jaeger-configuration
                  key: span-storage-type-persist
          resources:
            requests:
              memory: 100M
              cpu: 100m
            limits:
              memory: 100M
              cpu: 100m
      volumes:
        - configMap:
            name: jaeger-configuration
            items:
              - key: query
                path: query.yaml
          name: jaeger-configuration-volume
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: monitoring
  labels:
    app: jaeger
    jaeger-infra: query-service
spec:
  ports:
    - name: jaeger-query
      port: 16686
      targetPort: 16686
      protocol: TCP
  selector:
    jaeger-infra: query-pod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-ui
  namespace: monitoring
  annotations:
spec:
  rules:
    - host: jaeger-ui.local # your jaeger internal endpoint
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jaeger-query
              port:
                number: 16686
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  name: jaeger-collector-ingress
  namespace: monitoring
spec:
  rules:
    - host: jaeger-collector.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaeger-collector
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-ingester
  namespace: monitoring
  labels:
    app: jaeger
    jaeger-infra: ingester-deployment
spec:
  selector:
    matchLabels:
      app: jaeger-ingester
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jaeger-ingester
        jaeger-infra: ingester-pod
    spec:
      containers:
        - image: jaegertracing/jaeger-ingester:1.28 # 1.6.0
          name: jaeger-ingester
          args: ["--config-file=/conf/ingester.yaml"]
          ports:
            - containerPort: 14270
              protocol: TCP
            - containerPort: 14271
              protocol: TCP
          env:
            - name: INGESTER_PARALLELISM
              value: "1"
            - name: INGESTER_DEADLOCKINTERVAL
              value: ms
            - name: LOG_LEVEL
              value: debug
            - name: SPAN_STORAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: jaeger-configuration
                  key: span-storage-type-persist
            - name: METRICS_BACKEND
              value: expvar
          volumeMounts:
            - name: jaeger-configuration-volume
              mountPath: /conf
      hostAliases:
      - ip: "192.168.65.2"
        hostnames:
        - "kafka.local"
      volumes:
        - configMap:
            name: jaeger-configuration
            items:
              - key: ingester
                path: ingester.yaml
          name: jaeger-configuration-volume
