# https://gist.github.com/yusufsyaifudin/9265f28b9c8b66b145090787ca0fcb52#file-jaeger-component-kafka-yaml
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-deploy
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zoo1
#          image: digitalwonderland/zookeeper
          image: wurstmeister/zookeeper:3.4.6
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER
              value: zoo
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
---
apiVersion: v1
kind: Service
metadata:
  name: zoo
  namespace: infra
  labels:
    app: zookeeper
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: infra
  labels:
    name: kafka
spec:
  ports:
    - name: kafka-port
      port: 9092
      protocol: TCP
    - name: kafka-port2
      port: 29092
      protocol: TCP
  selector:
    app: kafka
    id: "0"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.12-2.3.0
#          image: confluentinc/cp-kafka
          ports:
            - containerPort: 9092
            - containerPort: 29092
          env:
            - name: KAFKA_CREATE_TOPICS
              value: jaeger-spans:1:1 # topic:partition:replicas
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo:2181
#            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
#              value: "1"
#            - name: KAFKA_BROKER_ID
#              value: "0"
              # confluentinc/cp-kafka
#            - name: KAFKA_ZOOKEEPER_CONNECT
#              value: zoo:2181
#            - name: ALLOW_PLAINTEXT_LISTENER
#              value: "yes"
#            - name: KAFKA_LISTENERS-INTERNAL
#              value: //kafka:29092,EXTERNAL://localhost:9092
#            - name: KAFKA_ADVERTISED_LISTENERS
#              value: INTERNAL://kafka-service:29092,EXTERNAL://localhost:9092
#            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
#              value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#            - name: KAFKA_INTER_BROKER_LISTENER_NAME
#              value: INTERNAL
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka
  namespace: infra
  annotations:
spec:
  rules:
    - host: kafka.local # your jaeger internal endpoint
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-service
                port:
                  number: 9092
